name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create gh-pages
        run: |
          mkdir gh-pages
          cp README.md gh-pages/
          echo "hereby.js.org" >> gh-pages/CNAME
          cat > gh-pages <<EOF
          plugins:
            - jekyll-relative-links
          relative_links:
            enabled: true
            collections: true
          include:
            - README.md
          EOF

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
